name: Java

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false

env:
  ALLURE_ENDPOINT: https://sandbox.testops.cloud/
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_PROJECT_ID: 35
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  #
  BRANCH: ${{ github.ref_name }}
  BROWSER: 'Chrome'
  ENDPOINT: 'sandbox.testops.cloud'
  OS: 'macOS'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set dynamic VERSION
        run: echo "VERSION=$(date +'%-y.%-m.%-d')" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
                 
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          ALLURE_ENDPOINT: ${{ env.ALLURE_ENDPOINT }}
          ALLURE_PROJECT_ID: ${{ env.ALLURE_PROJECT_ID }}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURECTL_VERSION: 1.0.2
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: allurectl watch -- ./gradlew clean test
        env:
          VERSION: ${{ env.VERSION }}
