name: Java

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false

env:
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  BRANCH: ${{ github.ref_name }}
  BROWSER: 'Chrome'
  ENDPOINT: 'sandbox.testops.cloud'
  OS: 'macOS'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set dynamic VERSION
        run: echo "VERSION=$(date +'%-y.%-m.%-d')" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
                 
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://sandbox.testops.cloud/
          allure-project-id: 35
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allurectl-version: 2.16.0
          #The latest version of allurectl is available at https://github.com/allure-framework/allurectl/releases
          
      - name: Run tests
        run: |
          chmod +x ./gradlew 
          allurectl watch -- ./gradlew clean test
        env:
          VERSION: ${{ env.VERSION }}
