name: Java

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Fetch latest allurectl version
        run: |
          latest_version=$(curl -s https://api.github.com/repos/allure-framework/allurectl/releases/latest | jq -r .tag_name)
          echo "ALLURECTL_VERSION=$latest_version" >> $GITHUB_ENV
                 
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://sandbox.testops.cloud/
          allure-project-id: 35
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allurectl-version: ${{ env.ALLURECTL_VERSION }}

      - name: Set dynamic VERSION
        run: echo "VERSION=$(date +'%-y.%-m.%-d')" >> $GITHUB_ENV
          
      - name: Run tests with Chrome
        run: |
          chmod +x ./gradlew 
          allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: "build/allure-results"
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          BRANCH: ${{ github.ref_name }}
          BROWSER: 'Chrome'
          ENDPOINT: 'sandbox.testops.cloud'
          OS: 'macOS'
          VERSION: ${{ env.VERSION }}

      - name: Run tests with Firefox
        run: |
          chmod +x ./gradlew 
          allurectl watch -- ./gradlew clean test
        env:
          ALLURE_RESULTS: "build/allure-results"
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          BRANCH: ${{ github.ref_name }}
          BROWSER: 'Firefox'
          ENDPOINT: 'sandbox.testops.cloud'
          OS: 'macOS'
          VERSION: ${{ env.VERSION }}
